import type { User, Timesheet, TimesheetEntry } from "@/types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alice Johnson",
    email: "alice@ticktock.dev",
    password: "password123",
    role: "admin",
  },
  {
    id: "user-2",
    name: "Bob Smith",
    email: "bob@ticktock.dev",
    password: "password123",
    role: "employee",
  },
  {
    id: "user-3",
    name: "Carol White",
    email: "carol@ticktock.dev",
    password: "password123",
    role: "employee",
  },
];

export const mockTimesheets: Timesheet[] = [
  {
    id: "ts-1",
    userId: "user-1",
    weekStart: "2025-04-28",
    weekEnd: "2025-05-04",
    totalHours: 38,
    status: "completed",
  },
  {
    id: "ts-2",
    userId: "user-1",
    weekStart: "2025-05-05",
    weekEnd: "2025-05-11",
    totalHours: 40,
    status: "missing",
  },
  {
    id: "ts-3",
    userId: "user-2",
    weekStart: "2025-04-28",
    weekEnd: "2025-05-04",
    totalHours: 35,
    status: "completed",
  },
  {
    id: "ts-4",
    userId: "user-2",
    weekStart: "2025-05-05",
    weekEnd: "2025-05-11",
    totalHours: 32,
    status: "incomplete",
  },
  {
    id: "ts-5",
    userId: "user-3",
    weekStart: "2025-04-28",
    weekEnd: "2025-05-04",
    totalHours: 40,
    status: "missing",
  },
  {
    id: "ts-6",
    userId: "user-3",
    weekStart: "2025-05-05",
    weekEnd: "2025-05-11",
    totalHours: 37,
    status: "incomplete",
  },
  {
    id: "ts-7",
    userId: "user-1",
    weekStart: "2026-01-04",
    weekEnd: "2026-01-10",
    totalHours: 42,
    status: "completed",
  },
  {
    id: "ts-8",
    userId: "user-1",
    weekStart: "2026-01-11",
    weekEnd: "2026-01-17",
    totalHours: 34,
    status: "incomplete",
  },
  {
    id: "ts-9",
    userId: "user-2",
    weekStart: "2026-01-04",
    weekEnd: "2026-01-10",
    totalHours: 40,
    status: "completed",
  },
  {
    id: "ts-10",
    userId: "user-2",
    weekStart: "2026-01-11",
    weekEnd: "2026-01-17",
    totalHours: 0,
    status: "missing",
  },
  {
    id: "ts-11",
    userId: "user-3",
    weekStart: "2026-01-04",
    weekEnd: "2026-01-10",
    totalHours: 38,
    status: "completed",
  },
  {
    id: "ts-12",
    userId: "user-3",
    weekStart: "2026-01-11",
    weekEnd: "2026-01-17",
    totalHours: 31,
    status: "incomplete",
  },
  {
    id: "ts-13",
    userId: "user-1",
    weekStart: "2026-01-18",
    weekEnd: "2026-01-24",
    totalHours: 41,
    status: "completed",
  },
  {
    id: "ts-14",
    userId: "user-2",
    weekStart: "2026-01-18",
    weekEnd: "2026-01-24",
    totalHours: 28,
    status: "incomplete",
  },
  {
    id: "ts-15",
    userId: "user-3",
    weekStart: "2026-01-18",
    weekEnd: "2026-01-24",
    totalHours: 0,
    status: "missing",
  },
  {
    id: "ts-16",
    userId: "user-1",
    weekStart: "2026-01-25",
    weekEnd: "2026-01-31",
    totalHours: 40,
    status: "completed",
  },
  {
    id: "ts-17",
    userId: "user-2",
    weekStart: "2026-01-25",
    weekEnd: "2026-01-31",
    totalHours: 35,
    status: "completed",
  },
  {
    id: "ts-18",
    userId: "user-3",
    weekStart: "2026-01-25",
    weekEnd: "2026-01-31",
    totalHours: 33,
    status: "incomplete",
  },
];

export const mockTimesheetEntries: TimesheetEntry[] = [
  // ts-1 — Alice, week 1
  {
    id: "e-1",
    timesheetId: "ts-1",
    date: "2025-04-28",
    project: "Project Alpha",
    task: "Frontend development",
    hours: 8,
    description: "Built login page components",
  },
  {
    id: "e-2",
    timesheetId: "ts-1",
    date: "2025-04-29",
    project: "Project Alpha",
    task: "Code review",
    hours: 6,
    description: "Reviewed PRs for sprint 3",
  },
  {
    id: "e-3",
    timesheetId: "ts-1",
    date: "2025-04-30",
    project: "Project Beta",
    task: "API integration",
    hours: 7.5,
    description: "Connected dashboard to REST API",
  },
  {
    id: "e-4",
    timesheetId: "ts-1",
    date: "2025-05-01",
    project: "Project Beta",
    task: "Testing",
    hours: 8,
    description: "Wrote unit tests for utils",
  },
  {
    id: "e-5",
    timesheetId: "ts-1",
    date: "2025-05-02",
    project: "Project Alpha",
    task: "Bug fixes",
    hours: 8.5,
    description: "Fixed layout issues on mobile",
  },

  // ts-2 — Alice, week 2
  {
    id: "e-6",
    timesheetId: "ts-2",
    date: "2025-05-05",
    project: "Project Alpha",
    task: "Feature development",
    hours: 8,
    description: "Implemented timesheet table",
  },
  {
    id: "e-7",
    timesheetId: "ts-2",
    date: "2025-05-06",
    project: "Project Beta",
    task: "Documentation",
    hours: 7,
    description: "Wrote API documentation",
  },
  {
    id: "e-8",
    timesheetId: "ts-2",
    date: "2025-05-07",
    project: "Project Alpha",
    task: "Meetings",
    hours: 8,
    description: "Sprint planning and retrospective",
  },
  {
    id: "e-9",
    timesheetId: "ts-2",
    date: "2025-05-08",
    project: "Project Beta",
    task: "Deployment",
    hours: 9,
    description: "Deployed staging environment",
  },
  {
    id: "e-10",
    timesheetId: "ts-2",
    date: "2025-05-09",
    project: "Project Alpha",
    task: "Code review",
    hours: 8,
    description: "Reviewed team PRs",
  },

  // ts-3 — Bob, week 1
  {
    id: "e-11",
    timesheetId: "ts-3",
    date: "2025-04-28",
    project: "Project Gamma",
    task: "Backend development",
    hours: 8,
    description: "Built REST endpoints",
  },
  {
    id: "e-12",
    timesheetId: "ts-3",
    date: "2025-04-29",
    project: "Project Gamma",
    task: "Database schema",
    hours: 7,
    description: "Designed timesheet DB tables",
  },
  {
    id: "e-13",
    timesheetId: "ts-3",
    date: "2025-04-30",
    project: "Project Gamma",
    task: "Testing",
    hours: 7,
    description: "Integration tests for API",
  },
  {
    id: "e-14",
    timesheetId: "ts-3",
    date: "2025-05-01",
    project: "Project Delta",
    task: "Meetings",
    hours: 6,
    description: "Client sync calls",
  },
  {
    id: "e-15",
    timesheetId: "ts-3",
    date: "2025-05-02",
    project: "Project Delta",
    task: "Research",
    hours: 7,
    description: "Evaluated authentication options",
  },

  // ts-4 — Bob, week 2
  {
    id: "e-16",
    timesheetId: "ts-4",
    date: "2025-05-05",
    project: "Project Gamma",
    task: "Backend development",
    hours: 8,
    description: "Implemented user service",
  },
  {
    id: "e-17",
    timesheetId: "ts-4",
    date: "2025-05-06",
    project: "Project Delta",
    task: "API integration",
    hours: 8,
    description: "Third-party calendar integration",
  },
  {
    id: "e-18",
    timesheetId: "ts-4",
    date: "2025-05-07",
    project: "Project Gamma",
    task: "Bug fixes",
    hours: 8,
    description: "Fixed session expiry bug",
  },
  {
    id: "e-19",
    timesheetId: "ts-4",
    date: "2025-05-08",
    project: "Project Delta",
    task: "Documentation",
    hours: 8,
    description: "Updated technical specs",
  },

  // ts-5 — Carol, week 1
  {
    id: "e-20",
    timesheetId: "ts-5",
    date: "2025-04-28",
    project: "Project Alpha",
    task: "UI design",
    hours: 8,
    description: "Designed dashboard mockups",
  },
  {
    id: "e-21",
    timesheetId: "ts-5",
    date: "2025-04-29",
    project: "Project Alpha",
    task: "Component development",
    hours: 9,
    description: "Built reusable UI components",
  },
  {
    id: "e-22",
    timesheetId: "ts-5",
    date: "2025-04-30",
    project: "Project Beta",
    task: "Accessibility",
    hours: 8,
    description: "ARIA attributes and keyboard nav",
  },
  {
    id: "e-23",
    timesheetId: "ts-5",
    date: "2025-05-01",
    project: "Project Beta",
    task: "Testing",
    hours: 7,
    description: "Cross-browser testing",
  },
  {
    id: "e-24",
    timesheetId: "ts-5",
    date: "2025-05-02",
    project: "Project Alpha",
    task: "Code review",
    hours: 8,
    description: "Reviewed design system PRs",
  },

  // ts-6 — Carol, week 2
  {
    id: "e-25",
    timesheetId: "ts-6",
    date: "2025-05-05",
    project: "Project Beta",
    task: "Frontend development",
    hours: 8,
    description: "Built modal components",
  },
  {
    id: "e-26",
    timesheetId: "ts-6",
    date: "2025-05-06",
    project: "Project Alpha",
    task: "Meetings",
    hours: 7,
    description: "Design system sync",
  },
  {
    id: "e-27",
    timesheetId: "ts-6",
    date: "2025-05-07",
    project: "Project Beta",
    task: "Documentation",
    hours: 7,
    description: "Component storybook docs",
  },
  {
    id: "e-28",
    timesheetId: "ts-6",
    date: "2025-05-08",
    project: "Project Alpha",
    task: "Bug fixes",
    hours: 7.5,
    description: "Responsive layout fixes",
  },
  {
    id: "e-29",
    timesheetId: "ts-6",
    date: "2025-05-09",
    project: "Project Beta",
    task: "Code review",
    hours: 7.5,
    description: "Reviewed accessibility PRs",
  },

  // ts-7 — Alice, 2026 week 1
  {
    id: "e-30",
    timesheetId: "ts-7",
    date: "2026-01-04",
    project: "Project Alpha",
    task: "Sprint kickoff",
    hours: 8,
    description: "Defined goals for the new quarter",
  },
  {
    id: "e-31",
    timesheetId: "ts-7",
    date: "2026-01-05",
    project: "Project Alpha",
    task: "Feature implementation",
    hours: 9,
    description: "Built onboarding workflow components",
  },
  {
    id: "e-32",
    timesheetId: "ts-7",
    date: "2026-01-06",
    project: "Project Beta",
    task: "API integration",
    hours: 8,
    description: "Connected reports page to backend services",
  },
  {
    id: "e-33",
    timesheetId: "ts-7",
    date: "2026-01-07",
    project: "Project Beta",
    task: "Testing",
    hours: 8,
    description: "Ran end-to-end QA for the new workflow",
  },
  {
    id: "e-34",
    timesheetId: "ts-7",
    date: "2026-01-08",
    project: "Project Alpha",
    task: "Bug fixes",
    hours: 9,
    description: "Resolved edge cases in the onboarding flow",
  },

  // ts-8 — Alice, 2026 week 2
  {
    id: "e-35",
    timesheetId: "ts-8",
    date: "2026-01-11",
    project: "Project Alpha",
    task: "Design review",
    hours: 7,
    description: "Reviewed updated component designs",
  },
  {
    id: "e-36",
    timesheetId: "ts-8",
    date: "2026-01-12",
    project: "Project Beta",
    task: "Documentation",
    hours: 6,
    description: "Updated API docs for the launch",
  },
  {
    id: "e-37",
    timesheetId: "ts-8",
    date: "2026-01-13",
    project: "Project Alpha",
    task: "Implementation",
    hours: 8,
    description: "Built automation for daily reporting",
  },
  {
    id: "e-38",
    timesheetId: "ts-8",
    date: "2026-01-14",
    project: "Project Beta",
    task: "Client support",
    hours: 6,
    description: "Helped clients with onboarding issues",
  },
  {
    id: "e-39",
    timesheetId: "ts-8",
    date: "2026-01-15",
    project: "Project Alpha",
    task: "Team planning",
    hours: 7,
    description: "Prepared the next sprint schedule",
  },

  // ts-9 — Bob, 2026 week 1
  {
    id: "e-40",
    timesheetId: "ts-9",
    date: "2026-01-04",
    project: "Project Gamma",
    task: "Backend architecture",
    hours: 8,
    description: "Designed scalable API endpoints",
  },
  {
    id: "e-41",
    timesheetId: "ts-9",
    date: "2026-01-05",
    project: "Project Gamma",
    task: "Database tuning",
    hours: 8,
    description: "Improved query performance for reporting",
  },
  {
    id: "e-42",
    timesheetId: "ts-9",
    date: "2026-01-06",
    project: "Project Delta",
    task: "API integration",
    hours: 8,
    description: "Connected analytics service to the backend",
  },
  {
    id: "e-43",
    timesheetId: "ts-9",
    date: "2026-01-07",
    project: "Project Delta",
    task: "Testing",
    hours: 8,
    description: "Validated new endpoint behavior",
  },
  {
    id: "e-44",
    timesheetId: "ts-9",
    date: "2026-01-08",
    project: "Project Gamma",
    task: "Release prep",
    hours: 8,
    description: "Deployed code and ran smoke tests",
  },

  // ts-10 — Bob, 2026 week 2 (missing)

  // ts-11 — Carol, 2026 week 1
  {
    id: "e-45",
    timesheetId: "ts-11",
    date: "2026-01-04",
    project: "Project Alpha",
    task: "UI refinement",
    hours: 8,
    description: "Fine-tuned interface layouts",
  },
  {
    id: "e-46",
    timesheetId: "ts-11",
    date: "2026-01-05",
    project: "Project Alpha",
    task: "Prototype build",
    hours: 8,
    description: "Implemented interactive dashboard elements",
  },
  {
    id: "e-47",
    timesheetId: "ts-11",
    date: "2026-01-06",
    project: "Project Beta",
    task: "Accessibility check",
    hours: 7,
    description: "Verified keyboard navigation and screen reader support",
  },
  {
    id: "e-48",
    timesheetId: "ts-11",
    date: "2026-01-07",
    project: "Project Beta",
    task: "User testing",
    hours: 8,
    description: "Collected feedback from early users",
  },
  {
    id: "e-49",
    timesheetId: "ts-11",
    date: "2026-01-08",
    project: "Project Alpha",
    task: "Visual polish",
    hours: 7,
    description: "Applied final design tweaks",
  },

  // ts-12 — Carol, 2026 week 2
  {
    id: "e-50",
    timesheetId: "ts-12",
    date: "2026-01-11",
    project: "Project Beta",
    task: "Documentation",
    hours: 7,
    description: "Created updated onboarding docs",
  },
  {
    id: "e-51",
    timesheetId: "ts-12",
    date: "2026-01-12",
    project: "Project Alpha",
    task: "Component build",
    hours: 8,
    description: "Built reusable form components",
  },
  {
    id: "e-52",
    timesheetId: "ts-12",
    date: "2026-01-13",
    project: "Project Alpha",
    task: "Team review",
    hours: 7,
    description: "Reviewed sprint progress with the team",
  },
  {
    id: "e-53",
    timesheetId: "ts-12",
    date: "2026-01-14",
    project: "Project Beta",
    task: "QA support",
    hours: 4,
    description: "Assisted with bug reproduction and fixes",
  },
  {
    id: "e-54",
    timesheetId: "ts-12",
    date: "2026-01-15",
    project: "Project Alpha",
    task: "Project planning",
    hours: 5,
    description: "Set priorities for the next sprint",
  },

  // ts-13 — Alice, 2026 week 3
  {
    id: "e-55",
    timesheetId: "ts-13",
    date: "2026-01-18",
    project: "Project Alpha",
    task: "Requirements review",
    hours: 8,
    description: "Reviewed feature requirements with stakeholders",
  },
  {
    id: "e-56",
    timesheetId: "ts-13",
    date: "2026-01-19",
    project: "Project Alpha",
    task: "Feature implementation",
    hours: 8,
    description: "Completed onboarding workflow enhancements",
  },
  {
    id: "e-57",
    timesheetId: "ts-13",
    date: "2026-01-20",
    project: "Project Beta",
    task: "Backend integration",
    hours: 8,
    description: "Integrated analytics into the dashboard",
  },
  {
    id: "e-58",
    timesheetId: "ts-13",
    date: "2026-01-21",
    project: "Project Beta",
    task: "Testing",
    hours: 8,
    description: "Verified the new analytics flow",
  },
  {
    id: "e-59",
    timesheetId: "ts-13",
    date: "2026-01-22",
    project: "Project Alpha",
    task: "Bug fixes",
    hours: 9,
    description: "Addressed data display issues",
  },

  // ts-14 — Bob, 2026 week 3
  {
    id: "e-60",
    timesheetId: "ts-14",
    date: "2026-01-18",
    project: "Project Gamma",
    task: "API maintenance",
    hours: 7,
    description: "Updated service health checks",
  },
  {
    id: "e-61",
    timesheetId: "ts-14",
    date: "2026-01-19",
    project: "Project Delta",
    task: "Team support",
    hours: 7,
    description: "Helped teammates troubleshoot backend errors",
  },
  {
    id: "e-62",
    timesheetId: "ts-14",
    date: "2026-01-20",
    project: "Project Gamma",
    task: "Code review",
    hours: 7,
    description: "Reviewed fixes from the previous sprint",
  },
  {
    id: "e-63",
    timesheetId: "ts-14",
    date: "2026-01-21",
    project: "Project Delta",
    task: "Documentation",
    hours: 7,
    description: "Documented service changes for the team",
  },

  // ts-15 — Carol, 2026 week 3 (missing)

  // ts-16 — Alice, 2026 week 4
  {
    id: "e-64",
    timesheetId: "ts-16",
    date: "2026-01-25",
    project: "Project Alpha",
    task: "Performance tuning",
    hours: 8,
    description: "Optimized page load times",
  },
  {
    id: "e-65",
    timesheetId: "ts-16",
    date: "2026-01-26",
    project: "Project Alpha",
    task: "Feature completion",
    hours: 8,
    description: "Finalized onboarding UI behavior",
  },
  {
    id: "e-66",
    timesheetId: "ts-16",
    date: "2026-01-27",
    project: "Project Beta",
    task: "Deployment prep",
    hours: 8,
    description: "Prepared release notes and build artifacts",
  },
  {
    id: "e-67",
    timesheetId: "ts-16",
    date: "2026-01-28",
    project: "Project Beta",
    task: "Testing",
    hours: 8,
    description: "Performed staging regression tests",
  },
  {
    id: "e-68",
    timesheetId: "ts-16",
    date: "2026-01-29",
    project: "Project Alpha",
    task: "Launch review",
    hours: 8,
    description: "Reviewed launch readiness with the product team",
  },

  // ts-17 — Bob, 2026 week 4
  {
    id: "e-69",
    timesheetId: "ts-17",
    date: "2026-01-25",
    project: "Project Gamma",
    task: "Schema updates",
    hours: 8,
    description: "Implemented database schema changes",
  },
  {
    id: "e-70",
    timesheetId: "ts-17",
    date: "2026-01-26",
    project: "Project Delta",
    task: "Performance work",
    hours: 8,
    description: "Improved API response times",
  },
  {
    id: "e-71",
    timesheetId: "ts-17",
    date: "2026-01-27",
    project: "Project Gamma",
    task: "Testing",
    hours: 8,
    description: "Validated schema changes in staging",
  },
  {
    id: "e-72",
    timesheetId: "ts-17",
    date: "2026-01-28",
    project: "Project Delta",
    task: "Support",
    hours: 8,
    description: "Resolved production incidents",
  },
  {
    id: "e-73",
    timesheetId: "ts-17",
    date: "2026-01-29",
    project: "Project Gamma",
    task: "Release prep",
    hours: 8,
    description: "Prepared the next deployment package",
  },

  // ts-18 — Carol, 2026 week 4
  {
    id: "e-74",
    timesheetId: "ts-18",
    date: "2026-01-25",
    project: "Project Alpha",
    task: "Component refinement",
    hours: 8,
    description: "Refined form components based on feedback",
  },
  {
    id: "e-75",
    timesheetId: "ts-18",
    date: "2026-01-26",
    project: "Project Beta",
    task: "Accessibility testing",
    hours: 8,
    description: "Ensured ARIA labels and keyboard nav were correct",
  },
  {
    id: "e-76",
    timesheetId: "ts-18",
    date: "2026-01-27",
    project: "Project Alpha",
    task: "Documentation",
    hours: 8,
    description: "Updated pattern library docs",
  },
  {
    id: "e-77",
    timesheetId: "ts-18",
    date: "2026-01-28",
    project: "Project Beta",
    task: "Bug fixes",
    hours: 4,
    description: "Resolved style regressions",
  },
  {
    id: "e-78",
    timesheetId: "ts-18",
    date: "2026-01-29",
    project: "Project Alpha",
    task: "Planning",
    hours: 5,
    description: "Scoped next sprint work",
  },
];
